<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-R8LNRUV" failures="1" tests="2" name="testCases.TestCase_SampleTest" time="199.007" errors="0" timestamp="2022-10-20T16:17:18 MYT" skipped="1">
  <testcase classname="testCases.TestCase_SampleTest" name="test_verify_title" time="83.029">
    <skipped/>
  </testcase> <!-- test_verify_title -->
  <system-out/>
  <testcase classname="testCases.TestCase_SampleTest" name="test_verify_title" time="115.978">
    <failure message="expected [HomePage] but found [Personal Banking | Savings, Credit Cards and Loans | CIMB SG]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [HomePage] but found [Personal Banking | Savings, Credit Cards and Loans | CIMB SG]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testCases.TestCase_SampleTest.test_verify_title(TestCase_SampleTest.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- test_verify_title -->
  <system-out/>
</testsuite> <!-- testCases.TestCase_SampleTest -->
