<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-R8LNRUV" name="testCases.TestCase_SampleTest" tests="2" failures="1" timestamp="2022-10-20T17:07:37 SGT" time="150.970" errors="0">
  <testcase name="test_verify_title" time="66.621" classname="testCases.TestCase_SampleTest">
    <failure type="java.lang.AssertionError" message="expected [HomePage] but found [Personal Banking | Savings, Credit Cards and Loans | CIMB SG]">
      <![CDATA[java.lang.AssertionError: expected [HomePage] but found [Personal Banking | Savings, Credit Cards and Loans | CIMB SG]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testCases.TestCase_SampleTest.test_verify_title(TestCase_SampleTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- test_verify_title -->
  <system-out/>
  <testcase name="test_verify_title" time="84.349" classname="testCases.TestCase_SampleTest">
    <skipped/>
  </testcase> <!-- test_verify_title -->
  <system-out/>
</testsuite> <!-- testCases.TestCase_SampleTest -->
